name: Coding Standards
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: none
        tools: composer:v2, cs2pr

    - name: Get Composer cache directory
      id: composer-cache-dir
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache PHP dependencies
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: Install PHP dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction

    - name: Run PHPCS
      run: |
        vendor/bin/phpcs -n -q --report=checkstyle . | cs2pr

  eslint:
    name: JavaScript Coding Standards
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache NPM dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install NPM modules
      run: npm install

    - name: Run ESLint
      run: npm run lint:js

  stylelint:
    name: CSS Coding Standards
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache NPM dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install NPM modules
      run: npm install

    - name: Run Stylelint
      run: npx stylelint --config=.stylelintrc.json --allow-empty-input --custom-formatter=node_modules/stylelint-formatter-github-annotate/dist/index.js "**/*.{css,scss}"
