name: Built and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - uses: alleyinteractive/action-release@develop
        with:
          skip-composer-install: true
